FROM registry.access.redhat.com/ubi8/go-toolset:1.19.10-10.1692783630
USER root
RUN yum install -y bind-utils net-tools procps jq
RUN git clone git://thekelleys.org.uk/dnsmasq.git
WORKDIR dnsmasq
RUN make
RUN make install
USER default
CMD dnsmasq -k -C /config/dnsmasq.cfg
